name: pytest

on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        include:
          - os: macos-latest
            pytest_args: --docker-fails --docker-strict
          - os: windows-latest
            pytest_args: --docker-fails # not strict since windows has docker partially available, just can't run linux containters
        exclude:
          - os: macos-latest
            python: "3.7" # does not exist for arm64 macos, which is now the macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install challtools
        run: |
          python -m pip install .
          python -m pip install pytest pytest-cov
      - name: pytest
        run: |
          pytest ${{ matrix.pytest_args }}
